title: Brayan Luque # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm an experienced data analyst, whith an analytical background and passionate analyze patterns and translate them into business insights.
  <br>
  Profficient in tools like SQL, BigQuery, Tableau, and Looker. 
  <br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/brayanluque/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://www.public.tableau.com/app/profile/brayan.luque">View My Tableau Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
