title: Brayan Luque # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 I'm an experienced data analyst, with an analytical background (industrial engineer), and passionate about analyzing patterns and translating them into business insights.
  <br>
  Proficient in several BI tools like SQL, BigQuery, Tableau, and Looker. 
  <br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/brayanluque/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.public.tableau.com/app/profile/brayan.luque">View My Tableau Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-CKBEH92Z4Z # your Google Analytics tracking ID here
